### PR TITLE
{dutch}.json

### PR DESCRIPTION
**Pull request by Cisko-Rijken**
I've tried to translate the English words into Dutch so specific and precise as possible for not every Dutchman understands English as well as most do. Hopefully the translation is better to comprehend for them.

Some words are indecisevly difficult to translate. This is because some words are best comprehended when kept in English. For the most part this is because sometimes these words are to technical.
But than again also because they are well understood by most Dutch people and is part of the anglicization of our language. 

Some of the words giving some difficulty may be:

summary: overzicht/ samengevat?/ sammenvatting?/ beknopt?
you: u/ je? (using u for being polite)
Wallet: portemonnee/ portefeuille?
Merchants: handelaars / kooplieden?/ 
update: bijgewerkt/ upgedate?
input: input/ ingang?
output: output/ uitgang?
Fee: fee/ vergoeding?/ beloning?
Sweep: Schoonvegen/ wegvegen?/ vegen?
Miners: Miners /mijnwerkers?
review: goedkeuren/ beoordelen
Unspend: Onbesteed(baar)/ niet-uitgegeven?/ onuitgegeven?

The first words given are the ones being used in this translation.

For me being a new Blockchain wallet user, I'll still getting used to the website and maybe stumble upon strange Dutch sentences. I will watch it and then review and change the dutch.json language file.

It's not really clear to me what the precise conventions are, when capital letters are used and with what words only.

However this translation may not be complete and may have to be revised once again.

Hopefully now the text is for every Dutchman to comprehend from young to old, new or experienced. 

Ofcourse I'm open to suggestions and any questions at all.

15mboYVYDrajekNY3ndWgV53QASzHMEsX1

### CODE REVIEW

**Comment by Sjors** [comment]
Thanks! I will leave comments on translations that need a bit more work.

@jtormey I'm not sure how this should be merged.

@Cisko-Rijken we are working on a completely new wallet. Would you be interested in helping us translate it?

The original English strings are here: https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/locales/en-human.json (give me some time to clean that up please)
The translations should go here: https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/locales/nl-human.json
There is an incomplete list of machine translations here that could be useful (duplicates need to be deleted): https://github.com/blockchain/My-Wallet-V3-Frontend/blob/master/locales/nl-robot.json

We're still working on improving this process.

**Comment by Sjors** [comment]
My list of comments below, however it might be more useful if you can help us out with the new wallet translations rather than improving the old ones.


"import_wallet" : "Importeer uw portemonnee naar de BlockChain" -> "Importeer uw portemonnee naar Blockchain" (original was wrong)

Translations that sound very American: usage, how_it_works, also_available, in_browser, confirm_email, most_advanced, full_control, ready

For example instead of:
"Na het inloggen wordt u gepresenteerd met uw saldo"
Try: 
"Nadat u ingelogd bent, ziet u uw saldo."

"Betaling notificaties" -> melding / bericht

"how_it_works" - the English "are you in the mood to know a little more?" is pretty tenenkrommend. Try something like: "Wilt u meer weten?"

"Denk eraan Blockchain is ook beschikbaar op:" -> "Blockchain is tevens beschikbaar voor: "

"Het verbazingwekkende is" : "Het mooie is"

"u kunt bitcoin direct in uw My Wallet-account in enkele seconden te deponeren" -> "u kunt direct bitcoin in uw wallet storten"

"de pers en de Specialisten" -> "pers en specialisten"

Other issues:
merchant -> winkelier (mostly physical or online shops)
wallet ->  consider using the English "wallet" instead of "portemonnee" that's what most Dutch people I meet say. 
sweep: "leeghalen"?
review: "controleer"?
unspend: "niet(-)uitgegeven", dus "(nog) niet uitgegeven outputs"
When in doubt, use the English term. That way people can find information on Google.

**Comment by Sjors** [comment]
https://alpha.blockchain.info/#/signup

**Comment by Cisko-Rijken** [comment]
I am very interested in helping to create this new wallet!

I wanted to review the adjustments I allready made. For I saw blockchain wallet in Dutch and saw a few things that needed change.

I became interested in the blockchain translation because of the sentence:

"Ben uw eigen bank"

I wrote an email to Jade at support:

"When I access your website's landing page ofcourse my IP is in Holland so the language on your site is Dutch. And most of it is correct, except for when I want to make a wallet. Clicking on Portemonnee (Wallet) it says:

"Ben uw eigen bank"

This very much, looks like a childish form of dutch, almost the same like: Am your own bank.

The correct sentence should be:

"Wees uw eigen bank"

http://woordenlijst.org/leidraad/11/7
https://translate.google.com/?hl=en&tab=TT#en/nl/be%20your%20own%20bank"

So thank you very much for this invitation!

**Comment by Cisko-Rijken** [comment]
I think it is important to have consistency in the typical tech savvy words used by the bitcoin community and especially  the translations of them for the Dutch people who don't understand English as much as most people do. Words like e-mail, download, input and so on, are words that most people now will understand. This is an ongoing process of anglicization.


 The other issues mentioned in your post:

merchant -> winkelier (mostly physical or online shops)

*Maybe indeed is this the best word for merchants?*
 
*In the translation I used* handelaars 

*But I thought of other words like* 

Kooplieden

wallet -> consider using the English "wallet" instead of "portemonnee" that's what most Dutch people I meet say. 

*That clears it up*

sweep: "leeghalen"?

*Maybe* 

Schoonvegen?

review: "controleer"?
 
*3 more words could also be used:*

Beoordeel?
Bekijk opnieuw?
Inspecteer?

*Of which I think* beoordeel *is best*

unspend: "niet(-)uitgegeven", dus "(nog) niet uitgegeven outputs"

*What do you think about:*

Onbesteedbaar?
Niet- besteed?

**Comment by tuzzolo** [comment]
Thanks for your contribution!

**Pull request merged**
